### PR TITLE
Remove a few more DAL dependencies.

### PR DESCRIPTION
**Pull request by markshannon**
Removes a few "#includes" and replaces `panic()` and `temperature()` with non-DAL versions.

### CODE REVIEW

**Comment by dpgeorge** [comment]
This looks ok, except that `panic()` has changed behaviour: it used to loop indefinitely and require a reset to restart the device, whereas now it restarts automatically after 1 second.  We should keep the original behaviour because this function is only ever called by the user and they must have wanted an infinite loop if they called the function.  We really don't want to change behaviour when we don't need to.

**Comment by markshannon** [comment]
I've made `panic()` act exactly the same as before, even using the same image.

**Comment by dpgeorge** [comment]
> I've made panic() act exactly the same as before, even using the same image.

I don't see the changes.... did you push them?

**Comment by markshannon** [comment]
Apparently not. I have now.

**Comment by dpgeorge** [comment]
Thanks!

**Pull request merged**
