### PR TITLE
Reaction game

### PR DESCRIPTION
**Pull request by samhandev**
@ntoll 
Updated @dsmclaughlin's reaction game from #111

This is currently working on the firmware.hex from https://github.com/ntoll/microrepl which still has the `display.animate` method.

It does seem like there have been changes to the `display` API to remove `animate`. I'm unable to build a newer hex from the code at https://github.com/bbcmicrobit/micropython code as the `yt up` command fails with the following message:

```
error: could not locate github component "lancaster-university/microbit-dal", either the name is misspelt, you do not have access to it, or it does not exist
```

### CODE REVIEW

**Comment by ntoll** [comment]
Use the latest version of Mu or uflash (which both contain the latest firmware).

http://github.com/ntoll/mu
http://github.com/ntoll/uflash

Hope this helps!

**Comment by markshannon** [comment]
@samhandev Could you update this to work with a recent (ideally the most recent version) of the firmware?
You'll need to change `display.animate` to `display.show` and retest it.

**Comment by samhandev** [comment]
Hey @ntoll @markshannon,

finally got round to updating the firmware using `http://github.com/ntoll/uflash`.

Tested and working.

**Comment by ntoll** [comment]
Can you squash/rebase these changes against master..? :-)

**Comment by dpgeorge** [comment]
Squashed to 2 commits to preserve authorship.  Merged in edf3e2890955a6bfd3b18e654d512335f6840e16 and de0f2410e1045fbbad91c4fb93a620f92ac67c24

**Pull request closed without merging**
