### PR TITLE
Create counter.py

### PR DESCRIPTION
**Pull request by zitterbewegung**
Simple counter for the bbc micro micro python for pedagogical purposes.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Did you try using the button.was_pressed() method?  That way you don't lose button presses during the scrolling of the number.  Actually, using button.get_presses() and button.reset_presses() would be even better.

Also, might be good to start the count so the first time you press the button a "1" scrolls across.

**Comment by ntoll** [comment]
@zitterbewegung again, care to revise in light of feedback..? Happy to help if need be...

**Comment by zitterbewegung** [comment]
Thank you @ntoll and @dpgeorge I have revised the python program upon your suggestions. Now it uses  button.get_presses() and button.reset_presses() and the counter is initialized to 1 .

**Comment by dpgeorge** [comment]
Please make it display "1" only after you press the button for the first time.  Please indent by 4 spaces.  Please squash all commits and rebase.  Sorry if I sound demanding!

**Comment by zitterbewegung** [comment]
Ok I have done the indentation and squash and rebased. Thanks for the input @dpgeorge I actually have never rebased and this was a good learning experience.

**Comment by dpgeorge** [comment]
@zitterbewegung nope, that didn't work.  You need to do something like this:
```
$ git checkout patch-2
$ git rebase -i master
(then leave the first commit starting with "pick" and make the rest start with "s" for squash)
$ git push --force
```

**Comment by zitterbewegung** [comment]
@dpgeorge Ok I believe i followed your directions and I only now have one commit that has my changes.

**Comment by dpgeorge** [comment]
@zitterbewegung that didn't work either... still 17 commits!  Anyway, not to worry, I squashed and rebased myself, merged in dabf4ecac73bb1b987a43c521911afc516980efc.

Note: I only merged the examples/counter.py script, not the other changes to the docs that are part of another PR.

**Pull request closed without merging**
