### PR TITLE
Update DAL to v1.4.19b.

### LINKED ISSUE #338: Firmware not compiling using yotta under Windows 10 (ninja)
Dear,

The actual master do not compile using Yotta.

System : 
- commit : bfaa52a2bb1c934a89202d44bb50172405a5b1bb 
- OS : Windows 10
- Yotta  : v023

Commands : 

```
$ git clone https://github.com/bbcmicrobit/micropython
$ cd micropython
$ yt target bbc-microbit-classic-gcc-nosd
$ yt up
$ yt build
```

Output : 

> (the long command)
> D:/Workspace/yotta/micropython/yotta_modules/ble-nrf51822/source/nRF5xGap.cpp: In member function 'virtual ble_error_t nRF5xGap::setWhitelist(const Gap::Whitelist_t&)':
> D:/Workspace/yotta/micropython/yotta_modules/ble-nrf51822/source/nRF5xGap.cpp:689:59: error: 'BLEProtocol::AddressType_t' is not a class or namespace
>          if (whitelistIn.addresses[i].type == BLEProtocol::AddressType_t::RANDOM_PRIVATE_NON_RESOLVABLE) {
>                                                            ^
> D:/Workspace/yotta/micropython/yotta_modules/ble-nrf51822/source/nRF5xGap.cpp: In member function 'ble_error_t nRF5xGap::generateStackWhitelist(ble_gap_whitelist_t&)':
> D:/Workspace/yotta/micropython/yotta_modules/ble-nrf51822/source/nRF5xGap.cpp:906:61: error: 'BLEProtocol::AddressType_t' is not a class or namespace
>          if (whitelistAddresses[i].addr_type == BLEProtocol::AddressType_t::RANDOM_PRIVATE_RESOLVABLE) {
>                                                              ^
> ninja: build stopped: subcommand failed.
> error: command ['ninja'] failed

### PR DESCRIPTION
**Pull request by dpgeorge**
This fixes a compile issue with the ble-nrf51822 component.

Will fix #338.

### CODE REVIEW

**Comment by markshannon** [comment]
Works on my machine.

**Comment by carlosperate** [comment]
Out of curiosity Mark, which OS and gcc version are you using?

**Comment by markshannon** [comment]
kubuntu linux 14.04
#99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016"
"GCC version is: 4.9.3"

**Comment by carlosperate** [comment]
Thanks Mark. Just to be sure, is that the normal gcc version? I should have clarified I meant the gcc-arm-none-eabi one.

**Comment by markshannon** [comment]
Yes, that the gcc-arm version number.

**Pull request merged**
