### PR TITLE
examples/smbus.py: SMBus commands

### PR DESCRIPTION
**Pull request by deshipu**
Adds an example class which implements the basic SMBus commands, as
present in the SMBus Python library for the Raspberry Pi.

Note that Block Read and Block Process call transactions should be
done with just two repeated starts, not three, but there is no way
to do it with the current microbit I2C API.

Implements #117

### CODE REVIEW

**Comment by markshannon** [comment]
OOI, what would need to be added to the i2c API in order to do Block Read and Block Process properly?

**Comment by deshipu** [comment]
I would need to be able to make a read without sending a start condition (or a stop condition), so that I can read the number of bytes to read, before actually reading those bytes.

**Comment by deshipu** [comment]
Basically something like:
```
self.i2c.write(self.addr, cmd.to_bytes(1) + count.to_bytes(1) + vals, repeat=True)
count = int.from_bytes(self.i2c.read(self.addr, 1, repeat=True))
return self.i2c.read(None, count)
```

**Comment by deshipu** [comment]
If I could also do a similar write, the expensive bytestring adding operation could be also replaced with three writes.

**Comment by dpgeorge** [comment]
> Note that Block Read and Block Process call transactions should be
> done with just two repeated starts, not three, but there is no way
> to do it with the current microbit I2C API.

I think you can do it by reading the maximum (32 bytes) and then truncating the result at the end.  Eg:
```python
    def read_block_data(self, cmd):
        """Perform a Block Read."""
        self.i2c.write(self.addr, cmd.to_bytes(1), repeat=True)
        data = self.i2c.read(self.addr, 32)
        return data[1 : (1 + data[0])]
```
The slave has no say as to how many bytes the master reads from it.  The master keeps reading until it sends a nack.

**Comment by deshipu** [comment]
Interesting, I will test that, thanks.

**Comment by abencomo** [comment]
Will this allow me to use the Pyboard with this VL53L0X sensor?

https://www.tindie.com/products/onehorse/vl53l0x-time-of-flight-ranging-sensor/

The interface is I2C, but the pyboard complains when I try to do "import smbus" and "import struct"

https://github.com/popunder/VL53L0X/blob/master/VL53L0Xtest.py

**Comment by deshipu** [comment]
@abencomo it is certainly possible to talk to that sensor from MicroBit, however, the library that you are trying was most likely written for Raspberry Pi, which has much more resources available (both in terms of memory and cpu speed). It is probably best to write a dedicated driver for MicroPython, that will take the limited resources into account. I wrote a driver for a very similar sensor, https://bitbucket.org/thesheep/micropython-vl6180/src/tip/vl6180.py -- you might be able to adapt it for your use using the information from the datasheet for your sensor.

Unfortunately I don't have a VL53L0X to test.

On another note, the "struct" module is available (in a limited form) on the pyboard as "ustruct". Unfortunately, "smbus" module is written specially for the microbit and will not work on pyboard.

**Comment by abencomo** [comment]
Thanks Radomir.  I'll try to adapt the vl6180.py and let you know if I got it working with VL53L0X sensor.

**Comment by dbrgn** [comment]
Any news on smbus support? :)

Would be great to have a `smbus` shim available that would make it possible to share driver code for the Raspberry Pi and for MicroPython boards.

**Pull request closed without merging**
