### PR TITLE
Fix music module so the ticker does nothing if module wasn't imported.

### PR DESCRIPTION
**Pull request by dpgeorge**
Otherwise the microbit can (and does for me) randomly crash just when sitting at the REPL.

### CODE REVIEW

**Comment by markshannon** [comment]
I'm surprised (and a bit worried) that 
a) I didn't catch that, and
b) it crashes randomly.
It ought to crash the instant `microbit_music_tick` is called.

**Comment by dpgeorge** [comment]
> b) it crashes randomly.

Yeah, I didn't get to the bottom of it.  But note that on bare-metal there's no such thing as a seg-fault, you're allowed to read from pretty much any memory location.  So it was probably reading the current `async_state` from location 0x00000008 and that location would eventually become non-zero and then it would go into the rest of the music ticker callback and then crash.

**Comment by ZanderBrown** [comment]
I see @dpgeorge has been busy today! Congrats on all the great work!

**Comment by markshannon** [comment]
Location 0x00000008 is in flash, so shouldn't be able to change. It's a mystery...

**Pull request merged**
