### PR TITLE
microbit recation game

### PR DESCRIPTION
**Pull request by dsmclaughlin**

### CODE REVIEW

**Comment by ntoll** [comment]
So this was created in a recent workshop at Python Sheffield. May I suggest we refactor this to use the `display.animate` function..?

**Comment by dsmclaughlin** [comment]
yes it was. I really wanted to do that but we ran out of time, now I dont have access to micro so how can I test to make sure the update is successful?

I thought submitting bad code was better than broken code :)

**Comment by ntoll** [comment]
:-)

There are several people who have devices who could make this work. If I get time I'll take a look.

**Comment by markshannon** [comment]
This looks it has been superseded by #226. @dsmclaughlin Any objections to closing this?

**Comment by dpgeorge** [comment]
Closing in favour of #226.

**Pull request closed without merging**
