### PR TITLE
Add os module with uname to form 1.0 release

### PR DESCRIPTION
**Pull request by markshannon**

### CODE REVIEW

**Comment by markshannon** [comment]
Fixes https://github.com/bbcmicrobit/micropython/issues/199

**Comment by dpgeorge** [comment]
Please see my comments on #272.  In particular, we shouldn't change anything in the inc/py or source/py directories.  That stuff comes from upstream.

**Comment by markshannon** [comment]
I've used the MP_DEFINE_ATTRTUPLE as you suggested.

**Comment by markshannon** [comment]
Updated to use `MICROPY_PY_SYS_PLATFORM`

**Pull request merged**
