### PR TITLE
Implement was_pressed, get_presses and reset for buttons.

### PR DESCRIPTION
**Pull request by markshannon**
This PR implements https://github.com/bbcmicrobit/micropython/issues/69.

As the DAL does not expose the functionality we require and I don't want any more hacks like:
https://github.com/bbcmicrobit/micropython/blob/master/source/microbit/microbitdisplay.cpp#L209
I've reimplemented the pin de-bouncing logic from the DAL and put it in a class of its own.

### CODE REVIEW

**Comment by dpgeorge** [comment]
If we wanted to use the DAL, couldn't we just listen on the message bus for wanted events and then set flags based on those?

Of course, what you've implemented here is much more efficient with memory (ie doesn't need to allocate on the heap whenever a button is pressed...) but I'm just thinking how to minimise divergence from the DAL.

**Comment by dpgeorge** [comment]
> As the DAL does not expose the functionality we require

Can you elaborate on this?

Note that if you set up the message bus events correctly, then the DAL does not allocate any heap memory on button event.

**Comment by markshannon** [comment]
I probably should have said "does not expose the functionality we require, without dragging in lots of unwanted dependencies." 
However, as it looks like we might be making some progress on https://github.com/lancaster-university/microbit-dal/issues/40, I'll revert to using events. At least, for now.

**Comment by markshannon** [comment]
And rebased.

**Comment by markshannon** [comment]
Rebased again...

**Comment by dpgeorge** [comment]
I think it's much better using the DAL.

**Pull request merged**
