### PR TITLE
Update storage.rst

### PR DESCRIPTION
**Pull request by Spadgerian**
print does nothing on the micro:bit. Replaced with display.scroll()
display.scroll(str(len(...))) or display.scroll(str(...)) added to aid displaying result

### CODE REVIEW

**Comment by deshipu** [comment]
You are mistaken. `print` does something: it outputs the text in the REPL, where it is much easier to read than on the scrolling display of the device.

**Comment by whaleygeek** [comment]
print() on micro:bit sends data to the serial port. This comes out in the
REPL window in Mu.

**Comment by Spadgerian** [comment]
Ok, sorry. I must have missed the REPL descriptions in the introduction.

**Comment by deshipu** [comment]
Thank you for the time you took to make those fixes though!

**Pull request closed without merging**
