### PR TITLE
Again add "active" to increase specificity

### PR DESCRIPTION
**Pull request by ScottDWebster**
The text is referring to active piezo buzzers that include their own oscillator to produce a predetermined frequency.  Passive piezo buzzers work just fine in this exercise.  Perhaps the previous page could be expanded slightly to give a brief explanation of the two types of piezo buzzers.

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Whats the relationship to #518?

**Comment by ScottDWebster** [comment]
Both io.html and music.html on http://microbit-micropython.readthedocs.io/en/latest/tutorials refer to "a piezo buzzer" when "an active piezo buzzer" is more correct and specific.  I have provided edits for both.

**Comment by ZanderBrown** [comment]
That didn't quite answer the question, looking at your commits they should really be in the same PR

Never mind

**Comment by ScottDWebster** [comment]
Sorry, I was just working with the web interface (from the "edit on Github link) and submitted them one at a time.  #518 refers to io.html and #519 refers to music.html.

**Pull request closed without merging**
