### PR TITLE
Avoid the word "scope"

### PR DESCRIPTION
**Pull request by ncoghlan**
"Scope" has a specific meaning in Python (in the sense of "variable
scope") so it's best to avoid it when discussing other concepts.

### CODE REVIEW

**Comment by ncoghlan** [comment]
The change to the "Movement" tutorial here refers to a "loop body", but the corresponding change to the previous introduction of scoping doesn't currently introduce that term: https://github.com/bbcmicrobit/micropython/pull/223

Perhaps it should? It's the right term for the concept that was previously being referred to as a scope.

**Comment by dpgeorge** [comment]
I'm happy with this.  @ntoll what about you?

**Comment by ntoll** [comment]
This is a great catch @ncoghlan. I'll take this branch, introduce "loop body" in an appropriate way, rebase and merge.

**Comment by ntoll** [comment]
Rebased and merged.

**Pull request closed without merging**
