### PR TITLE
Sphinx docs

### PR DESCRIPTION
**Pull request by deshipu**

### CODE REVIEW

**Comment by markshannon** [comment]
I've build the docs and they look the part.
I'll merge this tomorrow, unless someone says otherwise.

**Comment by ntoll** [comment]
Many apologies... I meant to look at this but "real work" has been a bit busy recently so I've not had the time. Please merge!

**Comment by markshannon** [comment]
OK in it goes.

**Comment by deshipu** [comment]
Great, thank you! I've setup bulding of the docs at http://microbit-micropython.readthedocs.org/
To force a rebuild, send a POST request to https://readthedocs.org/build/microbit-micropython -- I think it's possible to setup a hook in the github repository for that to happen after every commit.

**Pull request merged**
