### PR TITLE
flame simulation

### PR DESCRIPTION
**Pull request by Neon22**
text adj

### CODE REVIEW

**Comment by Neon22** [comment]
I just dont; get it - I unchecked everything except my changes.
My git-foo is so weak :(

**Comment by Neon22** [comment]
this was from a completely barand new checkout - deleted everything and still I can't get it to work.
I think I need to take up vagrancy instead of this computing lark.. Its time to go...

**Comment by dpgeorge** [comment]
Simplest thing would be to just: Copy your script out of the repo.  Delete the repo.  Clone it from scratch.  Copy back your script.  Add and commit it in a single commit.  Push.  Open PR.

**Comment by Neon22** [comment]
that's exactly what I did. :( trying again
thanks

**Comment by Neon22** [comment]
for the record - removing it doesn't delete any of the files in the local github folder :(
After manual delete - works as expected.

**Pull request closed without merging**
