### PR TITLE
Just a simple random student name picker to use for questioning in the classroom.

### PR DESCRIPTION
**Pull request by marcotranchino**

### CODE REVIEW

**Comment by deshipu** [comment]
Actually, I wonder if the examples should have proper, importable, python module names -- with underscores.

**Comment by marcotranchino** [comment]
OK, sounds good to me.

**Comment by ntoll** [comment]
Hi @marcotranchino the API has changed since this PR was created. For example, we've removed `microbit.random` and have a `random` module instead, including a `random.choice` method. Also, animations are a lot nicer / easier. Full docs here: http://microbit-micropython.readthedocs.org/en/latest/ Happy to help...

**Comment by marcotranchino** [comment]
No problem, I will change it. 
I have been using this program with 5 classes, with a pupil per class in charge of changing the names in the code and re-deploy. It works well, the students like it.

**Pull request closed without merging**
