### PR TITLE
docs: Alphabetise microbit module entries and use docstring notations.

### PR DESCRIPTION
**Pull request by microbit-carlos**
Content hasn't changed and this will help reduce conflicts with upcoming rebase of the `v2-docs` branch which also needs to do more changes to this file.

### CODE REVIEW

**Comment by microbit-carlos** [comment]
As the docs are slowing adopting the `:param :`, `:returns:`, etc docstrings notation I've updated this PR to include those changes for the micro:bit module. I've also added some additional information to be a bit more complete.

**Comment by microbit-carlos** [comment]
@microbit-mark could you have a quick review once you get a chance?
@dpgeorge I assume this kind of updates are generally good to go into the docs without major reviews?

**Comment by microbit-carlos** [comment]
Review URL: https://microbit-micropython--734.org.readthedocs.build/en/734/microbit.html

**Comment by microbit-mark** [comment]
👍🏻  LGTM hanks @microbit-carlos

**Pull request merged**
