### PR TITLE
Update to latest MicroPython core, v1.6-11.

### PR DESCRIPTION
**Pull request by dpgeorge**
Just a few bug fixes.

This is the newest v1.6 which was released yesterday.  Would be nice to have it part of microbit :)

### CODE REVIEW

**Comment by ntoll** [comment]
Build fails for me with latest master from DAL. :-(

```
/home/ntoll/src/microbit/microbit-micropython/source/microbit/microbitcompass.cpp: In function 'void* microbit_compass_calibrate(mp_obj_t)':
/home/ntoll/src/microbit/microbit-micropython/source/microbit/microbitcompass.cpp:53:60: error: 'MICROBIT_DISPLAY_REFRESH_PERIOD' was not declared in this scope
     uBit.systemTicker.attach(&uBit, &MicroBit::systemTick, MICROBIT_DISPLAY_REFRESH_PERIOD);
```

**Comment by dpgeorge** [comment]
That's a separate issue.  Looks like they just merged a whole lot of new stuff at Lancaster.......

**Comment by dpgeorge** [comment]
Commit added to get compiling against latest DAL.

**Comment by dpgeorge** [comment]
Added 3rd commit to fix examples now that microbit.random is gone.

**Comment by ntoll** [comment]
Yay. It works! :-) See - f6b08d0

**Comment by ntoll** [comment]
Damn... missed your recent update.

**Comment by dpgeorge** [comment]
No problem.

**Comment by ntoll** [comment]
Ugh... so Git wants to merge things despite me rebasing. I could just ``--force`` but that's not "nice".

**Comment by dpgeorge** [comment]
Rebased.

**Comment by ntoll** [comment]
Cheers

**Comment by markshannon** [comment]
@ntoll `--force` to master is really bad idea. Thanks for restraining yourself :+1:

**Pull request merged**
