### PR TITLE
Update pin.rst to accomodate PWM in the class definition for digital pins.

### PR DESCRIPTION
**Pull request by MrYsLab**
Update class descriptions in docs/pin.rst

### CODE REVIEW

**Comment by dpgeorge** [comment]
Thanks for the patch.

What is the reason to move the docs for write_digital() down to after set_pull()?  I would think that read_digital() and write_digital() are the most common and so that's why they are listed first.

**Comment by MrYsLab** [comment]
I thought it more logical to have digital input pin attributes grouped together, followed by digital write attributes, and finally followed by the analog (PWM) output attributes. 
My thought process is, is that a digital pin is a containment of three logical classes, digital input, digital output and analog output.
In my opinion, grouping by most common is less clear, and for me, adds confusion. But then again, I am easily confused ;-).

**Comment by MrYsLab** [comment]
@microbit-carlos I am not sure that I can resolve conflicts since it states above that "Only those with write access to this repository can merge pull requests."  When I click on Resolve conflicts, here is what I see as per the conflicts:
screenshot from 2018-10-11 15-40-14

Is there something I should be doing to help close this, or is this to be done on your end?
Thanks.

**Comment by microbit-carlos** [comment]
Hi @MrYsLab,
These conflicts are usually resolved using git locally on your computer and then pushing the changes to the branch. GH created a feature for their web interface to allow repository maintainers to be able to clear these conflicts online during a merge, and that's probably what you are seeing.

If you'd like to give this a go, you can merge master into your branch or git rebase, and then these are instructions on how to clear conflicts:
https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Comment by MrYsLab** [comment]
@microbit-carlos I modified the file to reflect the changes requested by @dpgeorge. I tried using the command line approach, but I don't think I have proper permissions. Could you please do the merge, or let me know what I can do to help.
Thanks.

**Comment by microbit-carlos** [comment]
@MrYsLab Because there has been some changes to the paragraphs about pull ups that you've moved and more changes will be included in the `get_pull()` method as part of https://github.com/bbcmicrobit/micropython/pull/578 I think the best path is to reduce the scope of this PR to just move the `write_analog()` `set_analog_period ()` and `set_analog_period_microseconds()` methods to `MicroBitDigitalPin` and leave everything as it was. 

If you create one more commit to do that, you can then squash all your commits into one (assuming you have 4 commits in total):
```
git reset --soft HEAD~4
git commit
```
And the you can pull from upstream master, hopefully, without conflicts
```
git remote add upstream https://github.com/bbcmicrobit/micropython.git
git pull upstream master
```
Check that the last commit looks good:
```
git log -p
```
And push to the branch you've used for this PR:
```
git push origin master --force
```

---

To be fair, it might be simpler to just do this from zero. In that case if you reset your master branch and then push that, this PR will contain whatever is in that branch.

First save your current branch and, delete your master branch and recreate it with a copy of the current upstream master:

```
git checkout -b old_version
git branch -D master
git remote add upstream https://github.com/bbcmicrobit/micropython.git
git checkout -b master upstream/master
```

Now you have a clean version of this master branch, you can add your changes here and once you have committed them:

```
git push origin master --force
```

**Comment by MrYsLab** [comment]
Ok. You should be able to merge with just the changes to the class definitions.

**Comment by microbit-carlos** [comment]
Yes, sorry for the delay and thanks for the poke, I'm still going through the PRs. Yours is good to go, so I'll merge it now, thank again @MrYsLab!

**Pull request merged**
