### PR TITLE
Fix error in compass.py script in examples.

### PR DESCRIPTION
**Pull request by ntoll**
What it says.

### CODE REVIEW

**Comment by dpgeorge** [comment]
I don't remember it even being "Images" with a plural...

**Comment by eaglestone** [comment]
The change from `Images` to `Image` does not seem to be coming through on the [docs site](https://microbit-micropython.readthedocs.org/en/latest/compass.html#example)?

**Comment by dpgeorge** [comment]
You need to retrigger a build of the docs manually.  Now done.

**Comment by eaglestone** [comment]
Thanks. Is that something I could have done?

**Comment by dpgeorge** [comment]
> Is that something I could have done?

Yes, anyone can do it.  But you've got to know the right things to click on :)

**Pull request merged**
