### PR TITLE
Only execute the initial script if in friendly-REPL mode.

### PR DESCRIPTION
**Pull request by dpgeorge**
This allows you to enter raw REPL mode (ctrl-A at the REPL) and prevent
the microbit from executing any code when it does a soft reboot.

### CODE REVIEW

**Comment by markshannon** [comment]
I haven't tested this, but it looks to me as if it has the same problem as before.
Suppose we start with a script running in "friendly" repl mode. Crtl-C is hit and a soft reboot occurs, but remains in "friendly" repl mode. The embedded script is then restarted and we're back to where we started.

**Comment by dpgeorge** [comment]
> Suppose we start with a script running in "friendly" repl mode. Crtl-C is hit and a soft reboot occurs, but remains in "friendly" repl mode.

Ctrl-C stops the script but does not do a soft reboot.  You then do ctrl-A to enter raw repl, then any soft reboot keeps it in raw repl without executing the script.

**Comment by markshannon** [comment]
Sorry for the delay. I've mapped out the state machine and this change does do what I want :+1: 
Does this need a rebase before merging?

**Comment by dpgeorge** [comment]
> I've mapped out the state machine and this change does do what I want

Great!

> Does this need a rebase before merging?

Nope, it's ready to merge.

**Comment by markshannon** [comment]
Ok, merging.

**Pull request merged**
