### PR TITLE
Raise an exception if i2c read/write fails.

### PR DESCRIPTION
**Pull request by markshannon**
Partial fix for https://github.com/bbcmicrobit/micropython/issues/119

### CODE REVIEW

**Comment by carlosperate** [comment]
We are currently looking at return error values for the UART module, and throwing an exception for the pin module  (if a digital pin write value is incorrect) and now the I2C. We should probably agree on a single way to deal with these kind of issues. Coming from an embedded background I am used to deal with return states, but throwing exceptions for erros is definitely more pythonic.

**Comment by dpgeorge** [comment]
> We should probably agree on a single way to deal with these kind of issues. Coming from an embedded background I am used to deal with return states, but throwing exceptions for erros is definitely more pythonic.

Raising an exception is, I think, exactly the right thing to do.  That's what Python is.

I am happy to merge this.

**Comment by markshannon** [comment]
Rebased.

**Comment by carlosperate** [comment]
> Raising an exception is, I think, exactly the right thing to do. That's what Python is.

I agree, we just need to remember to change the UART module as well then.

**Pull request merged**
