### PR TITLE
Update AUTHORS.txt

### PR DESCRIPTION
**Pull request by gbaman**
After suggestion to do so.

### CODE REVIEW

**Comment by dpgeorge** [comment]
Can you please point to one of your commits?

**Comment by ntoll** [comment]
@dpgeorge Andrew contributed a lot of work to the recent documentation updates (including example code as well as actual docs). 

Unfortunately, I spent an hour or so yesterday afternoon trying to merge / rebase cleanly between my docs branch, Andrew's alternative branch and master. There were a lot of conflicts that, for some as yet to be determined reason, kept re-appearing because git wasn't remembering/replaying how I'd resolved during a previous rebase. This happened several times and I found I was losing work as a result.

In the end I got so fed up with git I did a soft reset against master (thus losing the commit history) and wrapped all the changes into a single commit in my name.

This probably doesn't make sense, but essentially, Andrew has contributed a lot more code and docs than, say, Mariia (who is also in the README).

**Comment by dpgeorge** [comment]
Ok.  Did you mention @gbaman in the commit message?  That's usually the best way to credit other people's work that you needed to merge yourself.

**Comment by ntoll** [comment]
Unfortunately, not. :-/

**Comment by dpgeorge** [comment]
Ok.  Well make @gbaman can rebase this and change the commit message (not the first line but the discription bit after the first line) to be more descriptive and say something like "To acknowledge contribution to docs in 6de9704454b6c277ddfcd9e4f941f6d4a46e9ceb."

**Pull request closed without merging**
